from typing import TypedDict, List, Dict, Any, Optional

class PlatformState(TypedDict):
    """
    State contract for the Agentic Decision Intelligence Platform.
    Governs state flow and variable accumulation inside the LangGraph pipeline.
    """
    domain_pack: dict                  # Loaded DomainPack configuration details
    account: Optional[dict]            # The active customer/candidate record being analyzed

    retrieved_context: dict            # Context nodes retrieved from semantic/episodic memory
    reasoning_output: dict             # Findings, risks, and conflicts identified by Reasoning Agent
    recommendation_output: dict        # Set of candidate actions generated by Recommendation Agent
    explanation_output: dict           # Confidence scores and reasoning trace from Explanation Agent

    evidence: list                     # Accumulated EvidenceNode payloads
    confidence: dict                   # ComputedConfidence metrics dictionary

    human_feedback: Optional[dict]     # Feedback captured from the Human-in-the-loop gate

    metadata: dict                     # General execution metadata (timestamps, model paths, costs)
